#!/bin/bash
set -o errexit
set -o nounset

worker_ready(){
    celery -A real_estate inspect ping
}

until worker_ready; do 
    >&2 echo 'Celery workers not available :-('
    sleep 1
done

>&2 echo 'Celery workers are available! Starting Flower...'

celery -A real_estate flower \
    --port=5555 \
    --broker="${CELERY_BROKER_URL}"