#!/bin/bash
set -o errexit
set -o nounset

# Install watchdog first if needed
pip install watchdog || true

watchmedo auto-restart -d real_estate/ -p "*.py" -- \
    celery -A real_estate worker --loglevel=INFO