# Generated by Django 5.2 on 2025-04-19 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="user",
        ),
    ]
