# Generated by Django 5.2 on 2025-04-19 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_remove_property_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="agent_buyer",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Agent,Seller or Buyer",
            ),
            preserve_default=False,
        ),
    ]
