# Generated by Django 5.2 on 2025-04-19 12:45

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyviews',
            options={'verbose_name': 'Total Views on Property', 'verbose_name_plural': 'Total Property Views'},
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(default='Nairobi', max_length=180, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='property',
            name='country',
            field=django_countries.fields.CountryField(default='KE', max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='property',
            name='cover_photo',
            field=models.ImageField(blank=True, default='/house_sample.jpg', null=True, upload_to='', verbose_name='Main Photo'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(default='Default description...update me please....', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo1',
            field=models.ImageField(blank=True, default='/interior_sample.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo2',
            field=models.ImageField(blank=True, default='/interior_sample.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo3',
            field=models.ImageField(blank=True, default='/interior_sample.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo4',
            field=models.ImageField(blank=True, default='/interior_sample.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='postal_code',
            field=models.CharField(default='140', max_length=100, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Office', 'Office'), ('Warehouse', 'Warehouse'), ('Commercial', 'Commercial'), ('Other', 'Other')], default='Other', max_length=50, verbose_name='Property Type'),
        ),
        migrations.AlterField(
            model_name='property',
            name='street_address',
            field=models.CharField(default='KG8 Avenue', max_length=150, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_floors',
            field=models.IntegerField(default=0, verbose_name='Number of floors'),
        ),
        migrations.AlterField(
            model_name='property',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Total Views'),
        ),
    ]
