# Generated by Django 5.2 on 2025-04-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_agent",
            field=models.BooleanField(
                default=False, help_text="Are you an agent?", verbose_name="Agent"
            ),
        ),
    ]
