# Generated by Django 5.2 on 2025-04-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_profile_is_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="top_agent",
            field=models.BooleanField(
                default=False,
                help_text="Are you an Top agent?",
                verbose_name="Top Agent",
            ),
        ),
    ]
