# Generated by Django 5.2 on 2025-04-28 08:41

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_alter_profile_top_agent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="lincence",
        ),
        migrations.AddField(
            model_name="profile",
            name="license",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Real Estate license"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="about_me",
            field=models.TextField(
                default="say something about yourself", verbose_name="About me"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(
                default="Nairobi", max_length=180, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=django_countries.fields.CountryField(
                default="KE", max_length=2, verbose_name="Country"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                default="Other",
                max_length=20,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="is_buyer",
            field=models.BooleanField(
                default=False,
                help_text="Are you looking to Buy a Property?",
                verbose_name="Buyer",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_photo",
            field=models.ImageField(
                default="/profile_default.png",
                upload_to="",
                verbose_name="Profile Photo",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="top_agent",
            field=models.BooleanField(default=False, verbose_name="Top Agent"),
        ),
    ]
